[lastfm]
api_key = ""
api_secret = ""
username = ""
password_hash = ""

[spotify]
client_id = ""
client_secret = ""

# list of playlists that will be excluded from the update-playlists command
excluded_playlists = [
    # <playlist_id>,
    # ...
]

# list of playlists that will used as source for the discover-from-playlists command
sources_playlists = [
    # <playlist_id>,
    # ...
]

# personal playlist where new tracks will be added with the discover-from-playlists command
discover_playlist = "" # <playlist_id>
